version: '2'
services:
  tagsearch:
    container_name: tagsearch_backend
    build: .
    command: ./node_modules/.bin/jasmine JASMINE_CONFIG_PATH=backend/spec/jasmine.json
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/tagsearch
      - /var/lib/tagsearch
      - /home/app/tagsearch/node_modules
