version: '2'
services:
  node-server:
    container_name: search_routing
    build: .
    image: routing
    depends_on:
      - backend
  backend:
    container_name: search_service
    build: backend/.
    depends_on:
      - database
    command: node start-server.js
    environment:
      NODE_ENV: production
    ports:
      - '9200'
  database:
    container_name: search_database
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - '9200:9200'
    volumes:
      - ./backend/database/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - database:/usr/share/elasticsearch/data
volumes:
  database: { }

# Uses external network with routing
networks:
  default:
    external:
      name: production