version: '2'
services:
  node-server:
    container_name: routing
    build: .
    image: routing
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    container_name: search_service
    build: backend/.
    depends_on:
      - database
    command: node start-server.js
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
      - '9200'
  database:
    container_name: search_database
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - '9200:9200'
    volumes:
      - ./backend/database/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - database:/usr/share/elasticsearch/data
volumes:
  database: { }